name: Notify IRC
on:
  push:
  pull_request:
  create:
  issues:
    types: [opened, reopened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: irc push
        uses: vmiklos/notify-irc@a52a197c9507ad7a81c1a9295c9ed24786e396b3
        if: github.event_name == 'push'
        with:
          server: "irc.oftc.net"
          channel: "#smuxi"
          notice: true
          nickname: github-ci
          message: |
            ${{ toJson(github.event) }}
      - name: irc pull request
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'pull_request'
        with:
          server: "irc.oftc.net"
          channel: "#smuxi"
          notice: true
          nickname: github-ci
          message: |
            ${{ github.actor }} opened PR ${{ github.event.html_url }}
      - name: irc tag created
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        with:
          server: "irc.oftc.net"
          channel: "#smuxi"
          notice: true
          nickname: github-ci
          message: |
            ${{ github.actor }} tagged ${{ github.repository }} ${{ github.event.ref }}
      - name: irc issues
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'issues'
        with:
          server: "irc.oftc.net"
          channel: "#smuxi"
          notice: true
          nickname: github-ci
          message: |
            ${{ github.actor }} ${{ github.event.action }} issue #${{ github.event.issue.number }} in ${{ github.repository }} with title "${{ github.event.issue.title }}" ${{ github.event.issue.html_url }}
